[tool.poetry]
name = "web-analyzer"
version = "0.1.0"
description = ""
authors = ["Nikolas Schriefer <info@nikolasschriefer.de>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1"
flask-cors = "^3.0"
flask-script = "^2.0"
flask-restx = "^0.5"
flask-migrate = "^2.5"
flask-sqlalchemy = "^2.4"
psycopg2-binary = "2.8.6"  # 2.9 does not seem to be supported by AWS Lambda
zappa = "^0.54"
bs4 = "^0.0.1"
fuzzywuzzy = "^0.18"
python-Levenshtein = "^0.12"

[tool.poetry.dev-dependencies]
python-dotenv = "^0.19"
flake8 = "^4.0"
coverage = "^6.2"
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
