"""empty message

Revision ID: 855d2521d9b4
Revises: 644fd5404cf7
Create Date: 2021-06-15 16:34:54.951606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855d2521d9b4'
down_revision = '644fd5404cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('content', sa.String(), nullable=True))
    op.add_column('url', sa.Column('entities_response', sa.JSON(), nullable=True))
    op.add_column('url', sa.Column('artists_response', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url', 'artists_response')
    op.drop_column('url', 'entities_response')
    op.drop_column('url', 'content')
    # ### end Alembic commands ###
